# Generated by Django 3.2.10 on 2022-02-01 16:27

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20220110_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='expires_on',
            field=models.DateTimeField(default=post.models.create_expiration),
        ),
    ]
