# Generated by Django 3.2.10 on 2022-04-12 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20220307_2026'),
        ('post', '0011_auto_20220322_1507'),
    ]

    operations = [
    ]
