# Generated by Django 3.2.10 on 2022-04-12 00:57

from django.db import migrations, models
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_merge_0011_auto_20220307_2026_0011_auto_20220322_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownfield.models.MarkdownField(rendered_field='text_rendered', use_admin_editor=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
