# Generated by Django 3.2.10 on 2022-01-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='post',
        ),
        migrations.AddField(
            model_name='view',
            name='posts',
            field=models.ManyToManyField(to='post.Post'),
        ),
    ]
