# Generated by Django 3.2.10 on 2022-01-01 23:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0005_alter_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_left',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(related_name='views', to=settings.AUTH_USER_MODEL),
        ),
    ]
